### ISSUE TITLE
[Windows server 2025] Command prompt not showing

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#157]
I installed windows server 2025 and opening LVF but, logs is not showing

**Comment by chown2** [comment]
That is intentional. I think command prompt would look scary for a regular user. When developing on Windows, the debug output is now shown in Visual Studio, but the logs are always also available in the game's folder (LunaticVibesF*.log).

https://github.com/chown2/lunaticvibesf/commit/eac30f7d3147d4d21312772a5182a2c4d74cd512
https://github.com/chown2/lunaticvibesf/commit/b7a52f1ca26a175a9e2f0f7e988abab9a68064d5
