### ISSUE TITLE
Undefined Very Easy Judgment

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#30]
https://github.com/m8nscape/lunaticvibes/issues/45

**Comment by chown2** [comment]
I don't remember ever seeing such charts to be honest. Also, at least Remi-S and KCOOL skins don't seem to support such thing. Can you give me an example BMS file?  

As for the issue itself
https://github.com/chown2/lunaticvibesf/blob/0abc3c53b7a5531f294c023e3b96b45b3ed1fea3/src/game/ruleset/ruleset_bms.h#L86-L92

Also mentioned
https://github.com/chown2/lunaticvibesf/blob/0abc3c53b7a5531f294c023e3b96b45b3ed1fea3/src/game/ruleset/ruleset_bms.h#L35-L43

refactor pls
https://github.com/chown2/lunaticvibesf/blob/0abc3c53b7a5531f294c023e3b96b45b3ed1fea3/src/game/scene/scene_play.cpp#L790-L800

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/44b49252-5b98-4c19-a8eb-61c920c3e70f)
clone failure

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/d34e1852-7e63-490e-8946-7edd1cfd472f)
Clone failure also in VS2022

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/367873df-5f8c-4b8c-9b85-e960aea81413)
There are Judgment tables for LV
#RANK 5 is IIDX judge

**Comment by BKVad1m** [comment]
[New judgment rank.zip](https://github.com/chown2/lunaticvibesf/files/14927004/New.judgment.rank.zip)

**Comment by BKVad1m** [comment]
origin is nanasigroove from https://hitkey.nekokan.dyndns.info/cmds.htm

**Comment by chown2** [comment]
> clone failure

Probably there was some temporary GitHub failure, works fine for me

**Comment by chown2** [comment]
As far as I can tell, "Very Easy" isn't a thing in LR2. By my testing, when LR2 encounters invalid #RANK field, it just uses "EASY" judge, so I will consider this issue a bug in LVF's BMS parser.

Also, the "Very Easy" test file breaks LVF in a funny way - result shows 106.66% JUDGE RATE and FAILED instead of FULL COMBO, yet when you exit to song selection it shows "FULLCOMBO". 
EDIT: 106.66% - looks like a wrong number is shown on the result screen? On another chart I just had 8*2+8/32=75% rate, which is shown correctly after the fact in song selection, but on result it was shown as 80%.

**Comment by chown2** [comment]
Beatoraja has support for #RANK 4, says the timing windows are 1.2x times bigger than of "EASY" judge. If lr2oraja does the same, I'm open to implementing it.
https://github.com/exch-bms2/beatoraja/blob/f77e7389219555b0ac314196199bc653d8665de2/manual/extension.txt#L39-L41
