### ISSUE TITLE
[ImGui] Text input doesn't work after using song search

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#83]
https://github.com/chown2/lunaticvibesf/assets/76803825/2b616747-6222-4851-906d-54807973d84d

**Comment by chown2** [comment]
Reproducing:
Try typing in ImGui - all good.
Use song search.
Try typing in ImGui - keyboard text input not registered anymore (although arrow keys and backspace work).

SDL2 enables IME input by default (it won't be in SDL3).
We ask SDL2 to start/stop IME input when we enter/exit search box.
So, after using search, IME input is disabled, but ImGui relies on it always being enabled - it uses it for keyboard input, but it doesn't start/stop IME itself (since https://github.com/ocornut/imgui/commit/a7703fe6f74a78db58040813f9baae66b4fd053d; they reenabled that on SDL3 though https://github.com/ocornut/imgui/commit/fab96a6e59302fcaba2a17ea8d5a257a4fcf0d4f; issue itself is https://github.com/ocornut/imgui/issues/6306).
For now, I'll just stop starting/stopping IME input by hand on our side, but now I know we have a little bug IMO, that we can activate IME even outside of text input. :(
